name: Coverage Report Workflow

on:
  push:
    branches:
      - stable
      - development
  pull_request:
    branches:
      - stable
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Coverage report
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.08.1
      - run: opam pin add twostep.dev . --no-action
      - run: opam depext twostep --yes --with-test
      - run: opam install . --deps-only --with-doc --with-test
      - run: find . -name '*.coverage' | xargs rm -f
      - run: opam exec -- dune runtest --instrument-with bisect_ppx --force
      - run: opam exec -- bisect-ppx-report html --title twostep
      - run: opam exec -- bisect-ppx-report summary
      - run: opam exec -- bisect-ppx-report send-to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
      - run: opam install ocamlformat --yes
      - run: opam exec -- dune build @fmt
      - run: opam exec -- dune runtest
